name: international_phone_field
description: Validating numbers and providing necessary detail base on selected country 
version: 0.1.1
homepage: https://github.com/Rexfordasamoah51/international_phone_field

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  libphonenumber: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter


# The following section is specific to Flutter.
flutter: 
   uses-material-design: true
   assets:
        - assets/countries.json

